= Real-Time Fraud Detection with Data Microservices

=== Architecture overview

TODO

=== Requirements

  - CloudFoundry (tested with pcfdev v0.66)
  - Apache Geode (tested with v1.0.0-incubating.M2) - to be replaced by GemFire 9.0 when that is released
  - PostgreSQL (tested with 9.5.3) - to be replaced by Greenplum server once GemFire 9.0 is released
  - Spring Cloud Dataflow (tested with 1.0.0.M3)
  - Spark-redis (tested with v0.1.1) - install in local maven repository
  
=== Preparing the environment

* Export the variable __$GEODE_HOME__, pointing to your local GemFire / Geode server.
* Edit the file __start-scdf-pcfdev.sh__, in order to comply to your pcfdev environment and SCDF binaries path
* Edit the file __GemFireServer/startup.gfsh__, replacing the IPs with your local address on the pcfdev network (default is 192.168.11.1, and the pcfdev server would run on 192.168.11.11). If in doubt, check your pcfdev VM Ip address.
* Edit the file __TransactionsEmulator/src/main/resources/application.properties__, replacing the __geodeUrl__ variable with the correct Geode IP. 

[TODO: Remove the scdfUrl variable and manifest.yml from the TransactionEmulator] 


* Start pcfdev, if not running yet.
* Start Greenplum (or PostgreSQL)
* Use the DDL statements in __scripts/model_postgres.sql__ to create the database model
* Start GemFire/Geode using the script __GemFireServer/startup.sh__ 
* Start the Spring Cloud Dataflow server (or deploy it to pcfdev, if you prefer)

=== Running the app

==== Setup

1. Create the gemfire user-provided service in CF using the script __TransactionsConsole/cf-createservice.txt__ . If necessary, modify it to point to your correct GemFire server

2. Create the gpdb user-provided service in CF using the script __ClusteringService/cf-createservice.txt__ . If necessary, modify it to point to your correct Greenplum/PostgreSQL server

3. Push the app TransactionsConsole to CF. There's a __manifest.yml__ file on the application root folder.

4. Open the TransactionsConsole UI (see the CF assigned host, probably http://transactions-console.local.pcfdev.io) and notice the US Map. 

5. Now start the TransactionsEmulator app.  You can run __"./gradlew bootRun"__ to start it.  Wait for it to be done with loading the devices and transactions start to be posted.

6. Switch back to the TransactionsConsole UI and see transactions happening.


==== Creating and training the Machine Learning model

7. Push the application ClusteringService to CF. There's a __manifest.yml__ file on the application root folder.

8. Once the app is running, trigger the model training by accessing the __/clustering/train__ URL (probably http://clustering-service.local.pcfdev.io/clustering/train).  Check the CF logs for that app and see spark querying Greenplum/PostgreSQL and building the model.  It will take a few minutes until the model is trained and the URL will return a few numbers.

9. Now the model is trained, check its PMML representation using the url __/clustering/model.pmml.xml__ (http://clustering-service.local.pcfdev.io/clustering/model.pmml.xml)

10. Notice the clusters assigned by the bottom of the file 

[TODO: image] 

==== Creating the flow in SCDF ====








